package main

var pkgbuild_tests = []struct {
	name    string
	pkg     PkgBuild
	wantErr bool
	errMsg  string
}{
	{
		name: "valid package",
		pkg: PkgBuild{
			CliName:       "test",
			Maintainers:   []string{"Test User <test@example.com>"},
			Pkgname:       "test-bin",
			Version:       "1.0.0",
			Description:   "Test package",
			Url:           "https://example.com",
			Arch:          []string{"x86_64"},
			Licence:       []string{"MIT"},
			Source_x86_64: []string{"https://example.com/test"},
		},
		wantErr: false,
	},
	{
		name: "missing CliName",
		pkg: PkgBuild{
			Maintainers:   []string{"Test User"},
			Pkgname:       "test-bin",
			Version:       "1.0.0",
			Description:   "Test package",
			Url:           "https://example.com",
			Arch:          []string{"x86_64"},
			Licence:       []string{"MIT"},
			Source_x86_64: []string{"https://example.com/test"},
		},
		wantErr: true,
		errMsg:  "CliName is required",
	},
	{
		name: "missing Maintainers",
		pkg: PkgBuild{
			CliName:       "test",
			Pkgname:       "test-bin",
			Version:       "1.0.0",
			Description:   "Test package",
			Url:           "https://example.com",
			Arch:          []string{"x86_64"},
			Licence:       []string{"MIT"},
			Source_x86_64: []string{"https://example.com/test"},
		},
		wantErr: true,
		errMsg:  "At least one Maintainer is required",
	},
	{
		name: "missing Pkgname",
		pkg: PkgBuild{
			CliName:       "test",
			Maintainers:   []string{"Test User"},
			Version:       "1.0.0",
			Description:   "Test package",
			Url:           "https://example.com",
			Arch:          []string{"x86_64"},
			Licence:       []string{"MIT"},
			Source_x86_64: []string{"https://example.com/test"},
		},
		wantErr: true,
		errMsg:  "Pkgname is required",
	},
	{
		name: "missing Version",
		pkg: PkgBuild{
			CliName:       "test",
			Maintainers:   []string{"Test User"},
			Pkgname:       "test-bin",
			Description:   "Test package",
			Url:           "https://example.com",
			Arch:          []string{"x86_64"},
			Licence:       []string{"MIT"},
			Source_x86_64: []string{"https://example.com/test"},
		},
		wantErr: true,
		errMsg:  "Version is required",
	},
	{
		name: "missing Description",
		pkg: PkgBuild{
			CliName:       "test",
			Maintainers:   []string{"Test User"},
			Pkgname:       "test-bin",
			Version:       "1.0.0",
			Url:           "https://example.com",
			Arch:          []string{"x86_64"},
			Licence:       []string{"MIT"},
			Source_x86_64: []string{"https://example.com/test"},
		},
		wantErr: true,
		errMsg:  "Description is required",
	},
	{
		name: "missing Url",
		pkg: PkgBuild{
			CliName:       "test",
			Maintainers:   []string{"Test User"},
			Pkgname:       "test-bin",
			Version:       "1.0.0",
			Description:   "Test package",
			Arch:          []string{"x86_64"},
			Licence:       []string{"MIT"},
			Source_x86_64: []string{"https://example.com/test"},
		},
		wantErr: true,
		errMsg:  "Url is required",
	},
	{
		name: "missing Arch",
		pkg: PkgBuild{
			CliName:       "test",
			Maintainers:   []string{"Test User"},
			Pkgname:       "test-bin",
			Version:       "1.0.0",
			Description:   "Test package",
			Url:           "https://example.com",
			Licence:       []string{"MIT"},
			Source_x86_64: []string{"https://example.com/test"},
		},
		wantErr: true,
		errMsg:  "At least one Arch is required",
	},
	{
		name: "missing Licence",
		pkg: PkgBuild{
			CliName:       "test",
			Maintainers:   []string{"Test User"},
			Pkgname:       "test-bin",
			Version:       "1.0.0",
			Description:   "Test package",
			Url:           "https://example.com",
			Arch:          []string{"x86_64"},
			Source_x86_64: []string{"https://example.com/test"},
		},
		wantErr: true,
		errMsg:  "At least one Licence is required",
	},
	{
		name: "missing Source_x86_64",
		pkg: PkgBuild{
			CliName:     "test",
			Maintainers: []string{"Test User"},
			Pkgname:     "test-bin",
			Version:     "1.0.0",
			Description: "Test package",
			Url:         "https://example.com",
			Arch:        []string{"x86_64"},
			Licence:     []string{"MIT"},
		},
		wantErr: true,
		errMsg:  "Source_x86_64 is required",
	},
	{
		name: "optional fields can be empty",
		pkg: PkgBuild{
			CliName:        "test",
			Maintainers:    []string{"Test User"},
			Pkgname:        "test-bin",
			Version:        "1.0.0",
			Description:    "Test package",
			Url:            "https://example.com",
			Arch:           []string{"x86_64"},
			Licence:        []string{"MIT"},
			Source_x86_64:  []string{"https://example.com/test"},
			Contributors:   nil,
			Provides:       nil,
			Conflicts:      nil,
			Source_aarch64: nil,
		},
		wantErr: false,
	},
}
