name: Example Usage

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to test"
        required: true
        default: "0.1.1"

jobs:
  test-action-usage:
    name: Test Action as User Would Use It
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this action
        uses: actions/checkout@v4

      - name: Use this action
        uses: ./
        with:
          cli_name: pkgmate
          maintainers: "Fuad Daoud <aur@fuad-daoud.com>"
          pkgname: pkgmate-bin
          version: 0.1.1
          description: "TUI application to manage your dependencies"
          url: "https://github.com/fuad-daoud/pkgmate"
          arch: "x86_64"
          licence: "MIT"
          source_x86_64: "pkgmate-bin-0.1.1-x86_64::https://github.com/fuad-daoud/pkgmate/releases/download/0.1.1/pkgmate-linux-amd64"

      - name: Display generated PKGBUILD
        run: |
          echo "=== Generated PKGBUILD ==="
          cat output/PKGBUILD
          echo "=========================="

      - name: Validate PKGBUILD format
        run: |
          # Basic validation checks
          if ! grep -q "pkgname=pkgmate-bin" output/PKGBUILD; then
            echo "ERROR: pkgname not found"
            exit 1
          fi
          if ! grep -q "pkgver=${{ github.event.inputs.version }}" output/PKGBUILD; then
            echo "ERROR: pkgver not found"
            exit 1
          fi
          echo "✓ PKGBUILD validation passed"

      - name: Upload generated PKGBUILD
        uses: actions/upload-artifact@v4
        with:
          name: example-pkgbuild
          path: output/PKGBUILD
