name: Publish to Marketplace

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Publish to GitHub Marketplace
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate action.yml
        run: |
          echo "Validating action.yml structure..."
          
          # Check required fields
          if ! grep -q "^name:" action.yml; then
            echo "ERROR: Missing 'name' field"
            exit 1
          fi
          
          if ! grep -q "^description:" action.yml; then
            echo "ERROR: Missing 'description' field"
            exit 1
          fi
          
          if ! grep -q "^author:" action.yml; then
            echo "ERROR: Missing 'author' field"
            exit 1
          fi
          
          if ! grep -q "^branding:" action.yml; then
            echo "ERROR: Missing 'branding' section"
            exit 1
          fi
          
          echo "✓ action.yml validation passed"

      - name: Check for workflow files
        run: |
          # Marketplace requires no workflow files in root
          if ls *.yml 2>/dev/null | grep -v "action.yml" | grep -v "action.yaml"; then
            echo "WARNING: Found workflow files in root. These should be in .github/workflows/"
          fi
          echo "✓ No conflicting workflow files in root"

      - name: Test action
        uses: ./
        with:
          cli_name: 'test-cli'
          maintainers: 'Test <test@example.com>'
          pkgname: 'test-package'
          version: '1.0.0'
          description: 'Test package'
          url: 'https://github.com/test/test'
          arch: 'x86_64'
          licence: 'MIT'
          source_x86_64: 'https://example.com/test-1.0.0-x86_64'

      - name: Marketplace Publishing Instructions
        run: |
          echo "=========================================="
          echo "✓ Action is ready for GitHub Marketplace!"
          echo "=========================================="
          echo ""
          echo "To publish to Marketplace:"
          echo ""
          echo "1. Go to: https://github.com/${{ github.repository }}/releases/new"
          echo ""
          echo "2. Create a new release with:"
          echo "   - Tag: v1.0.0 (or your version)"
          echo "   - Title: Release v1.0.0"
          echo "   - Description: Initial release"
          echo ""
          echo "3. Check the box: ☑ Publish this Action to the GitHub Marketplace"
          echo ""
          echo "4. Select categories:"
          echo "   - Primary: Continuous integration"
          echo "   - Secondary: Publishing"
          echo ""
          echo "5. Click 'Publish release'"
          echo ""
          echo "=========================================="
          echo "Your action will be available at:"
          echo "https://github.com/marketplace/actions/release-to-aur"
          echo "=========================================="
